import React from "react";
import ReactMarkdown from "react-markdown";

/**
 * ReportDocument — A standalone, print-optimized component.
 * This is what gets rendered when the user clicks "Export PDF".
 * It's also embedded inside ReportViewer for on-screen display.
 */
export default function ReportDocument({ report, sources, topic, criticScore, revisionCount }) {
    return (
        <div className="report-document bg-white text-slate-900 font-serif">
            {/* Print-only header with metadata */}
            <div className="hidden print:block mb-8 pb-6 border-b-2 border-slate-200">
                <h1 className="text-3xl font-bold text-slate-900 mb-2">{topic}</h1>
                <div className="flex items-center gap-4 text-sm text-slate-500">
                    <span>Generated by AutoReport AI Agent</span>
                    <span>•</span>
                    <span>{new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
                    {criticScore > 0 && (
                        <>
                            <span>•</span>
                            <span>AI Critic Score: {criticScore}/10</span>
                        </>
                    )}
                    {revisionCount > 0 && (
                        <>
                            <span>•</span>
                            <span>{revisionCount} revision{revisionCount > 1 ? "s" : ""}</span>
                        </>
                    )}
                </div>
            </div>

            {/* Report Body */}
            <div className="prose prose-slate prose-emerald max-w-none
                prose-headings:font-bold prose-headings:font-sans
                prose-h1:text-3xl prose-h1:mb-6
                prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-3 prose-h2:border-b prose-h2:border-slate-200 prose-h2:pb-2
                prose-h3:text-lg prose-h3:mt-6
                prose-p:leading-relaxed prose-p:text-slate-700
                prose-a:text-emerald-600 prose-a:no-underline hover:prose-a:underline
                prose-li:text-slate-700
                prose-strong:text-slate-900
                print:prose-sm
            ">
                <ReactMarkdown>{report}</ReactMarkdown>
            </div>

            {/* Sources */}
            {sources && sources.length > 0 && (
                <div className="mt-12 pt-6 border-t-2 border-slate-200">
                    <h2 className="text-xl font-bold font-sans mb-4 text-slate-900">References</h2>
                    <ol className="space-y-2 text-sm text-slate-600 list-none p-0">
                        {sources.map((s, idx) => (
                            <li key={idx} className="break-all">
                                <span className="font-bold text-slate-800">[{idx + 1}]</span>{" "}
                                <a
                                    href={s.url}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="text-emerald-600 hover:underline"
                                >
                                    {s.title || s.url}
                                </a>
                                <span className="text-slate-400 text-xs ml-2 print:inline hidden">{s.url}</span>
                            </li>
                        ))}
                    </ol>
                </div>
            )}
        </div>
    );
}
